# Generated by Django 6.0.3 on 2026-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfounditerms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Documents', 'Documents'), ('Accessories', 'Accessories'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
