# Generated by Django 6.0.3 on 2026-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfounditerms', '0002_lostitem_category_lostitem_contact_lostitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=10),
        ),
    ]
